# Generated by Django 4.0.4 on 2022-05-18 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fscohort', '0006_student_birt_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='birt_date',
            field=models.DateField(),
        ),
    ]
