# Generated by Django 4.0.4 on 2022-05-15 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doritos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('surname', models.CharField(max_length=20)),
                ('mature', models.BooleanField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Types',
            new_name='Type',
        ),
    ]
